/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipperRouteImport } from './routes/shipper'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CarrierRouteImport } from './routes/carrier'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipperIndexRouteImport } from './routes/shipper.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as CarrierIndexRouteImport } from './routes/carrier.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShipperPaymentsRouteImport } from './routes/shipper.payments'
import { Route as ShipperEsgRouteImport } from './routes/shipper.esg'
import { Route as ShipperContractsRouteImport } from './routes/shipper.contracts'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverPanicRouteImport } from './routes/driver.panic'
import { Route as DriverHistoryRouteImport } from './routes/driver.history'
import { Route as DriverDocsRouteImport } from './routes/driver.docs'
import { Route as DriverDeliveryCompleteRouteImport } from './routes/driver.delivery-complete'
import { Route as DriverCheckpointRouteImport } from './routes/driver.checkpoint'
import { Route as CarrierVehiclesRouteImport } from './routes/carrier.vehicles'
import { Route as CarrierSettingsRouteImport } from './routes/carrier.settings'
import { Route as CarrierScoreRouteImport } from './routes/carrier.score'
import { Route as CarrierPayoutsRouteImport } from './routes/carrier.payouts'
import { Route as CarrierPaymentsRouteImport } from './routes/carrier.payments'
import { Route as CarrierMarketplaceRouteImport } from './routes/carrier.marketplace'
import { Route as CarrierFleetRouteImport } from './routes/carrier.fleet'
import { Route as CarrierDriversRouteImport } from './routes/carrier.drivers'
import { Route as CarrierBidsRouteImport } from './routes/carrier.bids'
import { Route as CarrierActiveRouteImport } from './routes/carrier.active'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminFreightsRouteImport } from './routes/admin.freights'
import { Route as AdminEsgRouteImport } from './routes/admin.esg'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminCarriersRouteImport } from './routes/admin.carriers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ShipperFreightsIndexRouteImport } from './routes/shipper.freights.index'
import { Route as CarrierTripsIndexRouteImport } from './routes/carrier.trips.index'
import { Route as CarrierContractsIndexRouteImport } from './routes/carrier.contracts.index'
import { Route as ShipperReviewContractIdRouteImport } from './routes/shipper.review.$contractId'
import { Route as ShipperPaymentContractIdRouteImport } from './routes/shipper.payment.$contractId'
import { Route as ShipperFreightsNewRouteImport } from './routes/shipper.freights.new'
import { Route as ShipperFreightsIdRouteImport } from './routes/shipper.freights.$id'
import { Route as ShipperContractsIdRouteImport } from './routes/shipper.contracts.$id'
import { Route as CarrierTripsIdRouteImport } from './routes/carrier.trips.$id'
import { Route as CarrierContractsIdRouteImport } from './routes/carrier.contracts.$id'

const ShipperRoute = ShipperRouteImport.update({
  id: '/shipper',
  path: '/shipper',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrierRoute = CarrierRouteImport.update({
  id: '/carrier',
  path: '/carrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipperIndexRoute = ShipperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShipperRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const CarrierIndexRoute = CarrierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarrierRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShipperPaymentsRoute = ShipperPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperEsgRoute = ShipperEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperContractsRoute = ShipperContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => ShipperRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverPanicRoute = DriverPanicRouteImport.update({
  id: '/panic',
  path: '/panic',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDocsRoute = DriverDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDeliveryCompleteRoute = DriverDeliveryCompleteRouteImport.update({
  id: '/delivery-complete',
  path: '/delivery-complete',
  getParentRoute: () => DriverRoute,
} as any)
const DriverCheckpointRoute = DriverCheckpointRouteImport.update({
  id: '/checkpoint',
  path: '/checkpoint',
  getParentRoute: () => DriverRoute,
} as any)
const CarrierVehiclesRoute = CarrierVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierSettingsRoute = CarrierSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierScoreRoute = CarrierScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierPayoutsRoute = CarrierPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierPaymentsRoute = CarrierPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierMarketplaceRoute = CarrierMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierFleetRoute = CarrierFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierDriversRoute = CarrierDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierBidsRoute = CarrierBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierActiveRoute = CarrierActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => CarrierRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFreightsRoute = AdminFreightsRouteImport.update({
  id: '/freights',
  path: '/freights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEsgRoute = AdminEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarriersRoute = AdminCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ShipperFreightsIndexRoute = ShipperFreightsIndexRouteImport.update({
  id: '/freights/',
  path: '/freights/',
  getParentRoute: () => ShipperRoute,
} as any)
const CarrierTripsIndexRoute = CarrierTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierContractsIndexRoute = CarrierContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => CarrierRoute,
} as any)
const ShipperReviewContractIdRoute = ShipperReviewContractIdRouteImport.update({
  id: '/review/$contractId',
  path: '/review/$contractId',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperPaymentContractIdRoute =
  ShipperPaymentContractIdRouteImport.update({
    id: '/payment/$contractId',
    path: '/payment/$contractId',
    getParentRoute: () => ShipperRoute,
  } as any)
const ShipperFreightsNewRoute = ShipperFreightsNewRouteImport.update({
  id: '/freights/new',
  path: '/freights/new',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperFreightsIdRoute = ShipperFreightsIdRouteImport.update({
  id: '/freights/$id',
  path: '/freights/$id',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperContractsIdRoute = ShipperContractsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShipperContractsRoute,
} as any)
const CarrierTripsIdRoute = CarrierTripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierContractsIdRoute = CarrierContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => CarrierRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrier': typeof CarrierRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shipper': typeof ShipperRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/freights': typeof AdminFreightsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/carrier/active': typeof CarrierActiveRoute
  '/carrier/bids': typeof CarrierBidsRoute
  '/carrier/drivers': typeof CarrierDriversRoute
  '/carrier/fleet': typeof CarrierFleetRoute
  '/carrier/marketplace': typeof CarrierMarketplaceRoute
  '/carrier/payments': typeof CarrierPaymentsRoute
  '/carrier/payouts': typeof CarrierPayoutsRoute
  '/carrier/score': typeof CarrierScoreRoute
  '/carrier/settings': typeof CarrierSettingsRoute
  '/carrier/vehicles': typeof CarrierVehiclesRoute
  '/driver/checkpoint': typeof DriverCheckpointRoute
  '/driver/delivery-complete': typeof DriverDeliveryCompleteRoute
  '/driver/docs': typeof DriverDocsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/panic': typeof DriverPanicRoute
  '/driver/profile': typeof DriverProfileRoute
  '/shipper/contracts': typeof ShipperContractsRouteWithChildren
  '/shipper/esg': typeof ShipperEsgRoute
  '/shipper/payments': typeof ShipperPaymentsRoute
  '/admin/': typeof AdminIndexRoute
  '/carrier/': typeof CarrierIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/shipper/': typeof ShipperIndexRoute
  '/carrier/contracts/$id': typeof CarrierContractsIdRoute
  '/carrier/trips/$id': typeof CarrierTripsIdRoute
  '/shipper/contracts/$id': typeof ShipperContractsIdRoute
  '/shipper/freights/$id': typeof ShipperFreightsIdRoute
  '/shipper/freights/new': typeof ShipperFreightsNewRoute
  '/shipper/payment/$contractId': typeof ShipperPaymentContractIdRoute
  '/shipper/review/$contractId': typeof ShipperReviewContractIdRoute
  '/carrier/contracts/': typeof CarrierContractsIndexRoute
  '/carrier/trips/': typeof CarrierTripsIndexRoute
  '/shipper/freights/': typeof ShipperFreightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/freights': typeof AdminFreightsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/carrier/active': typeof CarrierActiveRoute
  '/carrier/bids': typeof CarrierBidsRoute
  '/carrier/drivers': typeof CarrierDriversRoute
  '/carrier/fleet': typeof CarrierFleetRoute
  '/carrier/marketplace': typeof CarrierMarketplaceRoute
  '/carrier/payments': typeof CarrierPaymentsRoute
  '/carrier/payouts': typeof CarrierPayoutsRoute
  '/carrier/score': typeof CarrierScoreRoute
  '/carrier/settings': typeof CarrierSettingsRoute
  '/carrier/vehicles': typeof CarrierVehiclesRoute
  '/driver/checkpoint': typeof DriverCheckpointRoute
  '/driver/delivery-complete': typeof DriverDeliveryCompleteRoute
  '/driver/docs': typeof DriverDocsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/panic': typeof DriverPanicRoute
  '/driver/profile': typeof DriverProfileRoute
  '/shipper/contracts': typeof ShipperContractsRouteWithChildren
  '/shipper/esg': typeof ShipperEsgRoute
  '/shipper/payments': typeof ShipperPaymentsRoute
  '/admin': typeof AdminIndexRoute
  '/carrier': typeof CarrierIndexRoute
  '/driver': typeof DriverIndexRoute
  '/shipper': typeof ShipperIndexRoute
  '/carrier/contracts/$id': typeof CarrierContractsIdRoute
  '/carrier/trips/$id': typeof CarrierTripsIdRoute
  '/shipper/contracts/$id': typeof ShipperContractsIdRoute
  '/shipper/freights/$id': typeof ShipperFreightsIdRoute
  '/shipper/freights/new': typeof ShipperFreightsNewRoute
  '/shipper/payment/$contractId': typeof ShipperPaymentContractIdRoute
  '/shipper/review/$contractId': typeof ShipperReviewContractIdRoute
  '/carrier/contracts': typeof CarrierContractsIndexRoute
  '/carrier/trips': typeof CarrierTripsIndexRoute
  '/shipper/freights': typeof ShipperFreightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrier': typeof CarrierRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shipper': typeof ShipperRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/freights': typeof AdminFreightsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/carrier/active': typeof CarrierActiveRoute
  '/carrier/bids': typeof CarrierBidsRoute
  '/carrier/drivers': typeof CarrierDriversRoute
  '/carrier/fleet': typeof CarrierFleetRoute
  '/carrier/marketplace': typeof CarrierMarketplaceRoute
  '/carrier/payments': typeof CarrierPaymentsRoute
  '/carrier/payouts': typeof CarrierPayoutsRoute
  '/carrier/score': typeof CarrierScoreRoute
  '/carrier/settings': typeof CarrierSettingsRoute
  '/carrier/vehicles': typeof CarrierVehiclesRoute
  '/driver/checkpoint': typeof DriverCheckpointRoute
  '/driver/delivery-complete': typeof DriverDeliveryCompleteRoute
  '/driver/docs': typeof DriverDocsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/panic': typeof DriverPanicRoute
  '/driver/profile': typeof DriverProfileRoute
  '/shipper/contracts': typeof ShipperContractsRouteWithChildren
  '/shipper/esg': typeof ShipperEsgRoute
  '/shipper/payments': typeof ShipperPaymentsRoute
  '/admin/': typeof AdminIndexRoute
  '/carrier/': typeof CarrierIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/shipper/': typeof ShipperIndexRoute
  '/carrier/contracts/$id': typeof CarrierContractsIdRoute
  '/carrier/trips/$id': typeof CarrierTripsIdRoute
  '/shipper/contracts/$id': typeof ShipperContractsIdRoute
  '/shipper/freights/$id': typeof ShipperFreightsIdRoute
  '/shipper/freights/new': typeof ShipperFreightsNewRoute
  '/shipper/payment/$contractId': typeof ShipperPaymentContractIdRoute
  '/shipper/review/$contractId': typeof ShipperReviewContractIdRoute
  '/carrier/contracts/': typeof CarrierContractsIndexRoute
  '/carrier/trips/': typeof CarrierTripsIndexRoute
  '/shipper/freights/': typeof ShipperFreightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrier'
    | '/dashboard'
    | '/driver'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/shipper'
    | '/admin/audit'
    | '/admin/carriers'
    | '/admin/contracts'
    | '/admin/disputes'
    | '/admin/esg'
    | '/admin/freights'
    | '/admin/payments'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/carrier/active'
    | '/carrier/bids'
    | '/carrier/drivers'
    | '/carrier/fleet'
    | '/carrier/marketplace'
    | '/carrier/payments'
    | '/carrier/payouts'
    | '/carrier/score'
    | '/carrier/settings'
    | '/carrier/vehicles'
    | '/driver/checkpoint'
    | '/driver/delivery-complete'
    | '/driver/docs'
    | '/driver/history'
    | '/driver/panic'
    | '/driver/profile'
    | '/shipper/contracts'
    | '/shipper/esg'
    | '/shipper/payments'
    | '/admin/'
    | '/carrier/'
    | '/driver/'
    | '/shipper/'
    | '/carrier/contracts/$id'
    | '/carrier/trips/$id'
    | '/shipper/contracts/$id'
    | '/shipper/freights/$id'
    | '/shipper/freights/new'
    | '/shipper/payment/$contractId'
    | '/shipper/review/$contractId'
    | '/carrier/contracts/'
    | '/carrier/trips/'
    | '/shipper/freights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/admin/audit'
    | '/admin/carriers'
    | '/admin/contracts'
    | '/admin/disputes'
    | '/admin/esg'
    | '/admin/freights'
    | '/admin/payments'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/carrier/active'
    | '/carrier/bids'
    | '/carrier/drivers'
    | '/carrier/fleet'
    | '/carrier/marketplace'
    | '/carrier/payments'
    | '/carrier/payouts'
    | '/carrier/score'
    | '/carrier/settings'
    | '/carrier/vehicles'
    | '/driver/checkpoint'
    | '/driver/delivery-complete'
    | '/driver/docs'
    | '/driver/history'
    | '/driver/panic'
    | '/driver/profile'
    | '/shipper/contracts'
    | '/shipper/esg'
    | '/shipper/payments'
    | '/admin'
    | '/carrier'
    | '/driver'
    | '/shipper'
    | '/carrier/contracts/$id'
    | '/carrier/trips/$id'
    | '/shipper/contracts/$id'
    | '/shipper/freights/$id'
    | '/shipper/freights/new'
    | '/shipper/payment/$contractId'
    | '/shipper/review/$contractId'
    | '/carrier/contracts'
    | '/carrier/trips'
    | '/shipper/freights'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrier'
    | '/dashboard'
    | '/driver'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/shipper'
    | '/admin/audit'
    | '/admin/carriers'
    | '/admin/contracts'
    | '/admin/disputes'
    | '/admin/esg'
    | '/admin/freights'
    | '/admin/payments'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/carrier/active'
    | '/carrier/bids'
    | '/carrier/drivers'
    | '/carrier/fleet'
    | '/carrier/marketplace'
    | '/carrier/payments'
    | '/carrier/payouts'
    | '/carrier/score'
    | '/carrier/settings'
    | '/carrier/vehicles'
    | '/driver/checkpoint'
    | '/driver/delivery-complete'
    | '/driver/docs'
    | '/driver/history'
    | '/driver/panic'
    | '/driver/profile'
    | '/shipper/contracts'
    | '/shipper/esg'
    | '/shipper/payments'
    | '/admin/'
    | '/carrier/'
    | '/driver/'
    | '/shipper/'
    | '/carrier/contracts/$id'
    | '/carrier/trips/$id'
    | '/shipper/contracts/$id'
    | '/shipper/freights/$id'
    | '/shipper/freights/new'
    | '/shipper/payment/$contractId'
    | '/shipper/review/$contractId'
    | '/carrier/contracts/'
    | '/carrier/trips/'
    | '/shipper/freights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarrierRoute: typeof CarrierRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DriverRoute: typeof DriverRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShipperRoute: typeof ShipperRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipper': {
      id: '/shipper'
      path: '/shipper'
      fullPath: '/shipper'
      preLoaderRoute: typeof ShipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrier': {
      id: '/carrier'
      path: '/carrier'
      fullPath: '/carrier'
      preLoaderRoute: typeof CarrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipper/': {
      id: '/shipper/'
      path: '/'
      fullPath: '/shipper/'
      preLoaderRoute: typeof ShipperIndexRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/carrier/': {
      id: '/carrier/'
      path: '/'
      fullPath: '/carrier/'
      preLoaderRoute: typeof CarrierIndexRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shipper/payments': {
      id: '/shipper/payments'
      path: '/payments'
      fullPath: '/shipper/payments'
      preLoaderRoute: typeof ShipperPaymentsRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/esg': {
      id: '/shipper/esg'
      path: '/esg'
      fullPath: '/shipper/esg'
      preLoaderRoute: typeof ShipperEsgRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/contracts': {
      id: '/shipper/contracts'
      path: '/contracts'
      fullPath: '/shipper/contracts'
      preLoaderRoute: typeof ShipperContractsRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/panic': {
      id: '/driver/panic'
      path: '/panic'
      fullPath: '/driver/panic'
      preLoaderRoute: typeof DriverPanicRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/docs': {
      id: '/driver/docs'
      path: '/docs'
      fullPath: '/driver/docs'
      preLoaderRoute: typeof DriverDocsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/delivery-complete': {
      id: '/driver/delivery-complete'
      path: '/delivery-complete'
      fullPath: '/driver/delivery-complete'
      preLoaderRoute: typeof DriverDeliveryCompleteRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/checkpoint': {
      id: '/driver/checkpoint'
      path: '/checkpoint'
      fullPath: '/driver/checkpoint'
      preLoaderRoute: typeof DriverCheckpointRouteImport
      parentRoute: typeof DriverRoute
    }
    '/carrier/vehicles': {
      id: '/carrier/vehicles'
      path: '/vehicles'
      fullPath: '/carrier/vehicles'
      preLoaderRoute: typeof CarrierVehiclesRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/settings': {
      id: '/carrier/settings'
      path: '/settings'
      fullPath: '/carrier/settings'
      preLoaderRoute: typeof CarrierSettingsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/score': {
      id: '/carrier/score'
      path: '/score'
      fullPath: '/carrier/score'
      preLoaderRoute: typeof CarrierScoreRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/payouts': {
      id: '/carrier/payouts'
      path: '/payouts'
      fullPath: '/carrier/payouts'
      preLoaderRoute: typeof CarrierPayoutsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/payments': {
      id: '/carrier/payments'
      path: '/payments'
      fullPath: '/carrier/payments'
      preLoaderRoute: typeof CarrierPaymentsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/marketplace': {
      id: '/carrier/marketplace'
      path: '/marketplace'
      fullPath: '/carrier/marketplace'
      preLoaderRoute: typeof CarrierMarketplaceRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/fleet': {
      id: '/carrier/fleet'
      path: '/fleet'
      fullPath: '/carrier/fleet'
      preLoaderRoute: typeof CarrierFleetRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/drivers': {
      id: '/carrier/drivers'
      path: '/drivers'
      fullPath: '/carrier/drivers'
      preLoaderRoute: typeof CarrierDriversRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/bids': {
      id: '/carrier/bids'
      path: '/bids'
      fullPath: '/carrier/bids'
      preLoaderRoute: typeof CarrierBidsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/active': {
      id: '/carrier/active'
      path: '/active'
      fullPath: '/carrier/active'
      preLoaderRoute: typeof CarrierActiveRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/freights': {
      id: '/admin/freights'
      path: '/freights'
      fullPath: '/admin/freights'
      preLoaderRoute: typeof AdminFreightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/esg': {
      id: '/admin/esg'
      path: '/esg'
      fullPath: '/admin/esg'
      preLoaderRoute: typeof AdminEsgRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carriers': {
      id: '/admin/carriers'
      path: '/carriers'
      fullPath: '/admin/carriers'
      preLoaderRoute: typeof AdminCarriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shipper/freights/': {
      id: '/shipper/freights/'
      path: '/freights'
      fullPath: '/shipper/freights/'
      preLoaderRoute: typeof ShipperFreightsIndexRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/carrier/trips/': {
      id: '/carrier/trips/'
      path: '/trips'
      fullPath: '/carrier/trips/'
      preLoaderRoute: typeof CarrierTripsIndexRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/contracts/': {
      id: '/carrier/contracts/'
      path: '/contracts'
      fullPath: '/carrier/contracts/'
      preLoaderRoute: typeof CarrierContractsIndexRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/shipper/review/$contractId': {
      id: '/shipper/review/$contractId'
      path: '/review/$contractId'
      fullPath: '/shipper/review/$contractId'
      preLoaderRoute: typeof ShipperReviewContractIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/payment/$contractId': {
      id: '/shipper/payment/$contractId'
      path: '/payment/$contractId'
      fullPath: '/shipper/payment/$contractId'
      preLoaderRoute: typeof ShipperPaymentContractIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/freights/new': {
      id: '/shipper/freights/new'
      path: '/freights/new'
      fullPath: '/shipper/freights/new'
      preLoaderRoute: typeof ShipperFreightsNewRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/freights/$id': {
      id: '/shipper/freights/$id'
      path: '/freights/$id'
      fullPath: '/shipper/freights/$id'
      preLoaderRoute: typeof ShipperFreightsIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/contracts/$id': {
      id: '/shipper/contracts/$id'
      path: '/$id'
      fullPath: '/shipper/contracts/$id'
      preLoaderRoute: typeof ShipperContractsIdRouteImport
      parentRoute: typeof ShipperContractsRoute
    }
    '/carrier/trips/$id': {
      id: '/carrier/trips/$id'
      path: '/trips/$id'
      fullPath: '/carrier/trips/$id'
      preLoaderRoute: typeof CarrierTripsIdRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/contracts/$id': {
      id: '/carrier/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/carrier/contracts/$id'
      preLoaderRoute: typeof CarrierContractsIdRouteImport
      parentRoute: typeof CarrierRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCarriersRoute: typeof AdminCarriersRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminEsgRoute: typeof AdminEsgRoute
  AdminFreightsRoute: typeof AdminFreightsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCarriersRoute: AdminCarriersRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminEsgRoute: AdminEsgRoute,
  AdminFreightsRoute: AdminFreightsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CarrierRouteChildren {
  CarrierActiveRoute: typeof CarrierActiveRoute
  CarrierBidsRoute: typeof CarrierBidsRoute
  CarrierDriversRoute: typeof CarrierDriversRoute
  CarrierFleetRoute: typeof CarrierFleetRoute
  CarrierMarketplaceRoute: typeof CarrierMarketplaceRoute
  CarrierPaymentsRoute: typeof CarrierPaymentsRoute
  CarrierPayoutsRoute: typeof CarrierPayoutsRoute
  CarrierScoreRoute: typeof CarrierScoreRoute
  CarrierSettingsRoute: typeof CarrierSettingsRoute
  CarrierVehiclesRoute: typeof CarrierVehiclesRoute
  CarrierIndexRoute: typeof CarrierIndexRoute
  CarrierContractsIdRoute: typeof CarrierContractsIdRoute
  CarrierTripsIdRoute: typeof CarrierTripsIdRoute
  CarrierContractsIndexRoute: typeof CarrierContractsIndexRoute
  CarrierTripsIndexRoute: typeof CarrierTripsIndexRoute
}

const CarrierRouteChildren: CarrierRouteChildren = {
  CarrierActiveRoute: CarrierActiveRoute,
  CarrierBidsRoute: CarrierBidsRoute,
  CarrierDriversRoute: CarrierDriversRoute,
  CarrierFleetRoute: CarrierFleetRoute,
  CarrierMarketplaceRoute: CarrierMarketplaceRoute,
  CarrierPaymentsRoute: CarrierPaymentsRoute,
  CarrierPayoutsRoute: CarrierPayoutsRoute,
  CarrierScoreRoute: CarrierScoreRoute,
  CarrierSettingsRoute: CarrierSettingsRoute,
  CarrierVehiclesRoute: CarrierVehiclesRoute,
  CarrierIndexRoute: CarrierIndexRoute,
  CarrierContractsIdRoute: CarrierContractsIdRoute,
  CarrierTripsIdRoute: CarrierTripsIdRoute,
  CarrierContractsIndexRoute: CarrierContractsIndexRoute,
  CarrierTripsIndexRoute: CarrierTripsIndexRoute,
}

const CarrierRouteWithChildren =
  CarrierRoute._addFileChildren(CarrierRouteChildren)

interface DriverRouteChildren {
  DriverCheckpointRoute: typeof DriverCheckpointRoute
  DriverDeliveryCompleteRoute: typeof DriverDeliveryCompleteRoute
  DriverDocsRoute: typeof DriverDocsRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverPanicRoute: typeof DriverPanicRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverCheckpointRoute: DriverCheckpointRoute,
  DriverDeliveryCompleteRoute: DriverDeliveryCompleteRoute,
  DriverDocsRoute: DriverDocsRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverPanicRoute: DriverPanicRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface ShipperContractsRouteChildren {
  ShipperContractsIdRoute: typeof ShipperContractsIdRoute
}

const ShipperContractsRouteChildren: ShipperContractsRouteChildren = {
  ShipperContractsIdRoute: ShipperContractsIdRoute,
}

const ShipperContractsRouteWithChildren =
  ShipperContractsRoute._addFileChildren(ShipperContractsRouteChildren)

interface ShipperRouteChildren {
  ShipperContractsRoute: typeof ShipperContractsRouteWithChildren
  ShipperEsgRoute: typeof ShipperEsgRoute
  ShipperPaymentsRoute: typeof ShipperPaymentsRoute
  ShipperIndexRoute: typeof ShipperIndexRoute
  ShipperFreightsIdRoute: typeof ShipperFreightsIdRoute
  ShipperFreightsNewRoute: typeof ShipperFreightsNewRoute
  ShipperPaymentContractIdRoute: typeof ShipperPaymentContractIdRoute
  ShipperReviewContractIdRoute: typeof ShipperReviewContractIdRoute
  ShipperFreightsIndexRoute: typeof ShipperFreightsIndexRoute
}

const ShipperRouteChildren: ShipperRouteChildren = {
  ShipperContractsRoute: ShipperContractsRouteWithChildren,
  ShipperEsgRoute: ShipperEsgRoute,
  ShipperPaymentsRoute: ShipperPaymentsRoute,
  ShipperIndexRoute: ShipperIndexRoute,
  ShipperFreightsIdRoute: ShipperFreightsIdRoute,
  ShipperFreightsNewRoute: ShipperFreightsNewRoute,
  ShipperPaymentContractIdRoute: ShipperPaymentContractIdRoute,
  ShipperReviewContractIdRoute: ShipperReviewContractIdRoute,
  ShipperFreightsIndexRoute: ShipperFreightsIndexRoute,
}

const ShipperRouteWithChildren =
  ShipperRoute._addFileChildren(ShipperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarrierRoute: CarrierRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DriverRoute: DriverRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShipperRoute: ShipperRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
