/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportadorasRouteImport } from './routes/transportadoras'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ShipperRouteImport } from './routes/shipper'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriasRouteImport } from './routes/industrias'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CarrierRouteImport } from './routes/carrier'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipperIndexRouteImport } from './routes/shipper.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as CarrierIndexRouteImport } from './routes/carrier.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TransportadorasViagensRouteImport } from './routes/transportadoras_.viagens'
import { Route as TransportadorasHomologacaoRouteImport } from './routes/transportadoras_.homologacao'
import { Route as TecnologiaSteelCargoPassportRouteImport } from './routes/tecnologia_.steel-cargo-passport'
import { Route as TecnologiaOpenApiEcosystemRouteImport } from './routes/tecnologia_.open-api-ecosystem'
import { Route as TecnologiaDriverAppRouteImport } from './routes/tecnologia_.driver-app'
import { Route as TecnologiaComplianceSuiteRouteImport } from './routes/tecnologia_.compliance-suite'
import { Route as TecnologiaAiOrchestrationEngineRouteImport } from './routes/tecnologia_.ai-orchestration-engine'
import { Route as SuporteCanaisRouteImport } from './routes/suporte_.canais'
import { Route as SuporteAjudaRouteImport } from './routes/suporte_.ajuda'
import { Route as SolucoesSteelgoPlatformRouteImport } from './routes/solucoes_.steelgo-platform'
import { Route as SolucoesSteelgoPayRouteImport } from './routes/solucoes_.steelgo-pay'
import { Route as SolucoesSteelgoNetworkRouteImport } from './routes/solucoes_.steelgo-network'
import { Route as SolucoesManagedLogisticsRouteImport } from './routes/solucoes_.managed-logistics'
import { Route as SolucoesControlTowerRouteImport } from './routes/solucoes_.control-tower'
import { Route as SobreVisaoRouteImport } from './routes/sobre_.visao'
import { Route as SobrePilaresRouteImport } from './routes/sobre_.pilares'
import { Route as ShipperSettingsRouteImport } from './routes/shipper.settings'
import { Route as ShipperPaymentsRouteImport } from './routes/shipper.payments'
import { Route as ShipperEsgRouteImport } from './routes/shipper.esg'
import { Route as RecursosIntegracoesRouteImport } from './routes/recursos_.integracoes'
import { Route as RecursosGuiasRouteImport } from './routes/recursos_.guias'
import { Route as IndustriasVarejoRouteImport } from './routes/industrias_.varejo'
import { Route as IndustriasSiderurgicasRouteImport } from './routes/industrias_.siderurgicas'
import { Route as IndustriasIndustriaRouteImport } from './routes/industrias_.industria'
import { Route as IndustriasDistribuidoresRouteImport } from './routes/industrias_.distribuidores'
import { Route as EsgSteelgoGreenRouteImport } from './routes/esg_.steelgo-green'
import { Route as EsgIndicadoresRouteImport } from './routes/esg_.indicadores'
import { Route as EsgEficienciaRouteImport } from './routes/esg_.eficiencia'
import { Route as EsgCalculadoraRouteImport } from './routes/esg_.calculadora'
import { Route as DriverReturnReceiptRouteImport } from './routes/driver.return-receipt'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverPodRouteImport } from './routes/driver.pod'
import { Route as DriverPanicRouteImport } from './routes/driver.panic'
import { Route as DriverHistoryRouteImport } from './routes/driver.history'
import { Route as DriverExceptionRouteImport } from './routes/driver.exception'
import { Route as DriverDocsRouteImport } from './routes/driver.docs'
import { Route as DriverDeliveryCompleteRouteImport } from './routes/driver.delivery-complete'
import { Route as DriverCheckpointRouteImport } from './routes/driver.checkpoint'
import { Route as ContatoComercialRouteImport } from './routes/contato_.comercial'
import { Route as CarrierVehiclesRouteImport } from './routes/carrier.vehicles'
import { Route as CarrierSettingsRouteImport } from './routes/carrier.settings'
import { Route as CarrierScoreRouteImport } from './routes/carrier.score'
import { Route as CarrierPayoutsRouteImport } from './routes/carrier.payouts'
import { Route as CarrierPaymentsRouteImport } from './routes/carrier.payments'
import { Route as CarrierMarketplaceRouteImport } from './routes/carrier.marketplace'
import { Route as CarrierFleetRouteImport } from './routes/carrier.fleet'
import { Route as CarrierDriversRouteImport } from './routes/carrier.drivers'
import { Route as CarrierBidsRouteImport } from './routes/carrier.bids'
import { Route as CarrierActiveRouteImport } from './routes/carrier.active'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminFreightsRouteImport } from './routes/admin.freights'
import { Route as AdminEsgRouteImport } from './routes/admin.esg'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminCarriersRouteImport } from './routes/admin.carriers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ShipperTripsIndexRouteImport } from './routes/shipper.trips.index'
import { Route as ShipperFreightsIndexRouteImport } from './routes/shipper.freights.index'
import { Route as ShipperDisputesIndexRouteImport } from './routes/shipper.disputes.index'
import { Route as ShipperContractsIndexRouteImport } from './routes/shipper.contracts.index'
import { Route as CarrierTripsIndexRouteImport } from './routes/carrier.trips.index'
import { Route as CarrierDisputesIndexRouteImport } from './routes/carrier.disputes.index'
import { Route as CarrierContractsIndexRouteImport } from './routes/carrier.contracts.index'
import { Route as AdminOperationsIndexRouteImport } from './routes/admin.operations.index'
import { Route as AdminDisputesIndexRouteImport } from './routes/admin.disputes.index'
import { Route as ShipperTripsIdRouteImport } from './routes/shipper.trips.$id'
import { Route as ShipperReviewContractIdRouteImport } from './routes/shipper.review.$contractId'
import { Route as ShipperPaymentContractIdRouteImport } from './routes/shipper.payment.$contractId'
import { Route as ShipperFreightsNewRouteImport } from './routes/shipper.freights.new'
import { Route as ShipperFreightsIdRouteImport } from './routes/shipper.freights.$id'
import { Route as ShipperDisputesIdRouteImport } from './routes/shipper.disputes.$id'
import { Route as ShipperContractsIdRouteImport } from './routes/shipper.contracts.$id'
import { Route as CarrierTripsIdRouteImport } from './routes/carrier.trips.$id'
import { Route as CarrierDisputesIdRouteImport } from './routes/carrier.disputes.$id'
import { Route as CarrierContractsIdRouteImport } from './routes/carrier.contracts.$id'
import { Route as AdminOperationsGovernanceRouteImport } from './routes/admin.operations.governance'
import { Route as AdminOperationsIdRouteImport } from './routes/admin.operations.$id'
import { Route as AdminDisputesIdRouteImport } from './routes/admin.disputes.$id'

const TransportadorasRoute = TransportadorasRouteImport.update({
  id: '/transportadoras',
  path: '/transportadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipperRoute = ShipperRouteImport.update({
  id: '/shipper',
  path: '/shipper',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasRoute = IndustriasRouteImport.update({
  id: '/industrias',
  path: '/industrias',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrierRoute = CarrierRouteImport.update({
  id: '/carrier',
  path: '/carrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipperIndexRoute = ShipperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShipperRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const CarrierIndexRoute = CarrierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarrierRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TransportadorasViagensRoute = TransportadorasViagensRouteImport.update({
  id: '/transportadoras_/viagens',
  path: '/transportadoras/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportadorasHomologacaoRoute =
  TransportadorasHomologacaoRouteImport.update({
    id: '/transportadoras_/homologacao',
    path: '/transportadoras/homologacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const TecnologiaSteelCargoPassportRoute =
  TecnologiaSteelCargoPassportRouteImport.update({
    id: '/tecnologia_/steel-cargo-passport',
    path: '/tecnologia/steel-cargo-passport',
    getParentRoute: () => rootRouteImport,
  } as any)
const TecnologiaOpenApiEcosystemRoute =
  TecnologiaOpenApiEcosystemRouteImport.update({
    id: '/tecnologia_/open-api-ecosystem',
    path: '/tecnologia/open-api-ecosystem',
    getParentRoute: () => rootRouteImport,
  } as any)
const TecnologiaDriverAppRoute = TecnologiaDriverAppRouteImport.update({
  id: '/tecnologia_/driver-app',
  path: '/tecnologia/driver-app',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiaComplianceSuiteRoute =
  TecnologiaComplianceSuiteRouteImport.update({
    id: '/tecnologia_/compliance-suite',
    path: '/tecnologia/compliance-suite',
    getParentRoute: () => rootRouteImport,
  } as any)
const TecnologiaAiOrchestrationEngineRoute =
  TecnologiaAiOrchestrationEngineRouteImport.update({
    id: '/tecnologia_/ai-orchestration-engine',
    path: '/tecnologia/ai-orchestration-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuporteCanaisRoute = SuporteCanaisRouteImport.update({
  id: '/suporte_/canais',
  path: '/suporte/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteAjudaRoute = SuporteAjudaRouteImport.update({
  id: '/suporte_/ajuda',
  path: '/suporte/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSteelgoPlatformRoute = SolucoesSteelgoPlatformRouteImport.update({
  id: '/solucoes_/steelgo-platform',
  path: '/solucoes/steelgo-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSteelgoPayRoute = SolucoesSteelgoPayRouteImport.update({
  id: '/solucoes_/steelgo-pay',
  path: '/solucoes/steelgo-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSteelgoNetworkRoute = SolucoesSteelgoNetworkRouteImport.update({
  id: '/solucoes_/steelgo-network',
  path: '/solucoes/steelgo-network',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesManagedLogisticsRoute =
  SolucoesManagedLogisticsRouteImport.update({
    id: '/solucoes_/managed-logistics',
    path: '/solucoes/managed-logistics',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesControlTowerRoute = SolucoesControlTowerRouteImport.update({
  id: '/solucoes_/control-tower',
  path: '/solucoes/control-tower',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreVisaoRoute = SobreVisaoRouteImport.update({
  id: '/sobre_/visao',
  path: '/sobre/visao',
  getParentRoute: () => rootRouteImport,
} as any)
const SobrePilaresRoute = SobrePilaresRouteImport.update({
  id: '/sobre_/pilares',
  path: '/sobre/pilares',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipperSettingsRoute = ShipperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperPaymentsRoute = ShipperPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperEsgRoute = ShipperEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => ShipperRoute,
} as any)
const RecursosIntegracoesRoute = RecursosIntegracoesRouteImport.update({
  id: '/recursos_/integracoes',
  path: '/recursos/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosGuiasRoute = RecursosGuiasRouteImport.update({
  id: '/recursos_/guias',
  path: '/recursos/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasVarejoRoute = IndustriasVarejoRouteImport.update({
  id: '/industrias_/varejo',
  path: '/industrias/varejo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasSiderurgicasRoute = IndustriasSiderurgicasRouteImport.update({
  id: '/industrias_/siderurgicas',
  path: '/industrias/siderurgicas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasIndustriaRoute = IndustriasIndustriaRouteImport.update({
  id: '/industrias_/industria',
  path: '/industrias/industria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasDistribuidoresRoute =
  IndustriasDistribuidoresRouteImport.update({
    id: '/industrias_/distribuidores',
    path: '/industrias/distribuidores',
    getParentRoute: () => rootRouteImport,
  } as any)
const EsgSteelgoGreenRoute = EsgSteelgoGreenRouteImport.update({
  id: '/esg_/steelgo-green',
  path: '/esg/steelgo-green',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgIndicadoresRoute = EsgIndicadoresRouteImport.update({
  id: '/esg_/indicadores',
  path: '/esg/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgEficienciaRoute = EsgEficienciaRouteImport.update({
  id: '/esg_/eficiencia',
  path: '/esg/eficiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgCalculadoraRoute = EsgCalculadoraRouteImport.update({
  id: '/esg_/calculadora',
  path: '/esg/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverReturnReceiptRoute = DriverReturnReceiptRouteImport.update({
  id: '/return-receipt',
  path: '/return-receipt',
  getParentRoute: () => DriverRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverPodRoute = DriverPodRouteImport.update({
  id: '/pod',
  path: '/pod',
  getParentRoute: () => DriverRoute,
} as any)
const DriverPanicRoute = DriverPanicRouteImport.update({
  id: '/panic',
  path: '/panic',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverRoute,
} as any)
const DriverExceptionRoute = DriverExceptionRouteImport.update({
  id: '/exception',
  path: '/exception',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDocsRoute = DriverDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDeliveryCompleteRoute = DriverDeliveryCompleteRouteImport.update({
  id: '/delivery-complete',
  path: '/delivery-complete',
  getParentRoute: () => DriverRoute,
} as any)
const DriverCheckpointRoute = DriverCheckpointRouteImport.update({
  id: '/checkpoint',
  path: '/checkpoint',
  getParentRoute: () => DriverRoute,
} as any)
const ContatoComercialRoute = ContatoComercialRouteImport.update({
  id: '/contato_/comercial',
  path: '/contato/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrierVehiclesRoute = CarrierVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierSettingsRoute = CarrierSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierScoreRoute = CarrierScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierPayoutsRoute = CarrierPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierPaymentsRoute = CarrierPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierMarketplaceRoute = CarrierMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierFleetRoute = CarrierFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierDriversRoute = CarrierDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierBidsRoute = CarrierBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierActiveRoute = CarrierActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => CarrierRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFreightsRoute = AdminFreightsRouteImport.update({
  id: '/freights',
  path: '/freights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEsgRoute = AdminEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarriersRoute = AdminCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ShipperTripsIndexRoute = ShipperTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperFreightsIndexRoute = ShipperFreightsIndexRouteImport.update({
  id: '/freights/',
  path: '/freights/',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperDisputesIndexRoute = ShipperDisputesIndexRouteImport.update({
  id: '/disputes/',
  path: '/disputes/',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperContractsIndexRoute = ShipperContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => ShipperRoute,
} as any)
const CarrierTripsIndexRoute = CarrierTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierDisputesIndexRoute = CarrierDisputesIndexRouteImport.update({
  id: '/disputes/',
  path: '/disputes/',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierContractsIndexRoute = CarrierContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => CarrierRoute,
} as any)
const AdminOperationsIndexRoute = AdminOperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesIndexRoute = AdminDisputesIndexRouteImport.update({
  id: '/disputes/',
  path: '/disputes/',
  getParentRoute: () => AdminRoute,
} as any)
const ShipperTripsIdRoute = ShipperTripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperReviewContractIdRoute = ShipperReviewContractIdRouteImport.update({
  id: '/review/$contractId',
  path: '/review/$contractId',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperPaymentContractIdRoute =
  ShipperPaymentContractIdRouteImport.update({
    id: '/payment/$contractId',
    path: '/payment/$contractId',
    getParentRoute: () => ShipperRoute,
  } as any)
const ShipperFreightsNewRoute = ShipperFreightsNewRouteImport.update({
  id: '/freights/new',
  path: '/freights/new',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperFreightsIdRoute = ShipperFreightsIdRouteImport.update({
  id: '/freights/$id',
  path: '/freights/$id',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperDisputesIdRoute = ShipperDisputesIdRouteImport.update({
  id: '/disputes/$id',
  path: '/disputes/$id',
  getParentRoute: () => ShipperRoute,
} as any)
const ShipperContractsIdRoute = ShipperContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => ShipperRoute,
} as any)
const CarrierTripsIdRoute = CarrierTripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierDisputesIdRoute = CarrierDisputesIdRouteImport.update({
  id: '/disputes/$id',
  path: '/disputes/$id',
  getParentRoute: () => CarrierRoute,
} as any)
const CarrierContractsIdRoute = CarrierContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => CarrierRoute,
} as any)
const AdminOperationsGovernanceRoute =
  AdminOperationsGovernanceRouteImport.update({
    id: '/operations/governance',
    path: '/operations/governance',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOperationsIdRoute = AdminOperationsIdRouteImport.update({
  id: '/operations/$id',
  path: '/operations/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesIdRoute = AdminDisputesIdRouteImport.update({
  id: '/disputes/$id',
  path: '/disputes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrier': typeof CarrierRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRouteWithChildren
  '/esg': typeof EsgRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industrias': typeof IndustriasRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recursos': typeof RecursosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shipper': typeof ShipperRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/suporte': typeof SuporteRoute
  '/tecnologia': typeof TecnologiaRoute
  '/terms': typeof TermsRoute
  '/transportadoras': typeof TransportadorasRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/freights': typeof AdminFreightsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/carrier/active': typeof CarrierActiveRoute
  '/carrier/bids': typeof CarrierBidsRoute
  '/carrier/drivers': typeof CarrierDriversRoute
  '/carrier/fleet': typeof CarrierFleetRoute
  '/carrier/marketplace': typeof CarrierMarketplaceRoute
  '/carrier/payments': typeof CarrierPaymentsRoute
  '/carrier/payouts': typeof CarrierPayoutsRoute
  '/carrier/score': typeof CarrierScoreRoute
  '/carrier/settings': typeof CarrierSettingsRoute
  '/carrier/vehicles': typeof CarrierVehiclesRoute
  '/contato/comercial': typeof ContatoComercialRoute
  '/driver/checkpoint': typeof DriverCheckpointRoute
  '/driver/delivery-complete': typeof DriverDeliveryCompleteRoute
  '/driver/docs': typeof DriverDocsRoute
  '/driver/exception': typeof DriverExceptionRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/panic': typeof DriverPanicRoute
  '/driver/pod': typeof DriverPodRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/return-receipt': typeof DriverReturnReceiptRoute
  '/esg/calculadora': typeof EsgCalculadoraRoute
  '/esg/eficiencia': typeof EsgEficienciaRoute
  '/esg/indicadores': typeof EsgIndicadoresRoute
  '/esg/steelgo-green': typeof EsgSteelgoGreenRoute
  '/industrias/distribuidores': typeof IndustriasDistribuidoresRoute
  '/industrias/industria': typeof IndustriasIndustriaRoute
  '/industrias/siderurgicas': typeof IndustriasSiderurgicasRoute
  '/industrias/varejo': typeof IndustriasVarejoRoute
  '/recursos/guias': typeof RecursosGuiasRoute
  '/recursos/integracoes': typeof RecursosIntegracoesRoute
  '/shipper/esg': typeof ShipperEsgRoute
  '/shipper/payments': typeof ShipperPaymentsRoute
  '/shipper/settings': typeof ShipperSettingsRoute
  '/sobre/pilares': typeof SobrePilaresRoute
  '/sobre/visao': typeof SobreVisaoRoute
  '/solucoes/control-tower': typeof SolucoesControlTowerRoute
  '/solucoes/managed-logistics': typeof SolucoesManagedLogisticsRoute
  '/solucoes/steelgo-network': typeof SolucoesSteelgoNetworkRoute
  '/solucoes/steelgo-pay': typeof SolucoesSteelgoPayRoute
  '/solucoes/steelgo-platform': typeof SolucoesSteelgoPlatformRoute
  '/suporte/ajuda': typeof SuporteAjudaRoute
  '/suporte/canais': typeof SuporteCanaisRoute
  '/tecnologia/ai-orchestration-engine': typeof TecnologiaAiOrchestrationEngineRoute
  '/tecnologia/compliance-suite': typeof TecnologiaComplianceSuiteRoute
  '/tecnologia/driver-app': typeof TecnologiaDriverAppRoute
  '/tecnologia/open-api-ecosystem': typeof TecnologiaOpenApiEcosystemRoute
  '/tecnologia/steel-cargo-passport': typeof TecnologiaSteelCargoPassportRoute
  '/transportadoras/homologacao': typeof TransportadorasHomologacaoRoute
  '/transportadoras/viagens': typeof TransportadorasViagensRoute
  '/admin/': typeof AdminIndexRoute
  '/carrier/': typeof CarrierIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/shipper/': typeof ShipperIndexRoute
  '/admin/disputes/$id': typeof AdminDisputesIdRoute
  '/admin/operations/$id': typeof AdminOperationsIdRoute
  '/admin/operations/governance': typeof AdminOperationsGovernanceRoute
  '/carrier/contracts/$id': typeof CarrierContractsIdRoute
  '/carrier/disputes/$id': typeof CarrierDisputesIdRoute
  '/carrier/trips/$id': typeof CarrierTripsIdRoute
  '/shipper/contracts/$id': typeof ShipperContractsIdRoute
  '/shipper/disputes/$id': typeof ShipperDisputesIdRoute
  '/shipper/freights/$id': typeof ShipperFreightsIdRoute
  '/shipper/freights/new': typeof ShipperFreightsNewRoute
  '/shipper/payment/$contractId': typeof ShipperPaymentContractIdRoute
  '/shipper/review/$contractId': typeof ShipperReviewContractIdRoute
  '/shipper/trips/$id': typeof ShipperTripsIdRoute
  '/admin/disputes/': typeof AdminDisputesIndexRoute
  '/admin/operations/': typeof AdminOperationsIndexRoute
  '/carrier/contracts/': typeof CarrierContractsIndexRoute
  '/carrier/disputes/': typeof CarrierDisputesIndexRoute
  '/carrier/trips/': typeof CarrierTripsIndexRoute
  '/shipper/contracts/': typeof ShipperContractsIndexRoute
  '/shipper/disputes/': typeof ShipperDisputesIndexRoute
  '/shipper/freights/': typeof ShipperFreightsIndexRoute
  '/shipper/trips/': typeof ShipperTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/esg': typeof EsgRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industrias': typeof IndustriasRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recursos': typeof RecursosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/suporte': typeof SuporteRoute
  '/tecnologia': typeof TecnologiaRoute
  '/terms': typeof TermsRoute
  '/transportadoras': typeof TransportadorasRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/freights': typeof AdminFreightsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/carrier/active': typeof CarrierActiveRoute
  '/carrier/bids': typeof CarrierBidsRoute
  '/carrier/drivers': typeof CarrierDriversRoute
  '/carrier/fleet': typeof CarrierFleetRoute
  '/carrier/marketplace': typeof CarrierMarketplaceRoute
  '/carrier/payments': typeof CarrierPaymentsRoute
  '/carrier/payouts': typeof CarrierPayoutsRoute
  '/carrier/score': typeof CarrierScoreRoute
  '/carrier/settings': typeof CarrierSettingsRoute
  '/carrier/vehicles': typeof CarrierVehiclesRoute
  '/contato/comercial': typeof ContatoComercialRoute
  '/driver/checkpoint': typeof DriverCheckpointRoute
  '/driver/delivery-complete': typeof DriverDeliveryCompleteRoute
  '/driver/docs': typeof DriverDocsRoute
  '/driver/exception': typeof DriverExceptionRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/panic': typeof DriverPanicRoute
  '/driver/pod': typeof DriverPodRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/return-receipt': typeof DriverReturnReceiptRoute
  '/esg/calculadora': typeof EsgCalculadoraRoute
  '/esg/eficiencia': typeof EsgEficienciaRoute
  '/esg/indicadores': typeof EsgIndicadoresRoute
  '/esg/steelgo-green': typeof EsgSteelgoGreenRoute
  '/industrias/distribuidores': typeof IndustriasDistribuidoresRoute
  '/industrias/industria': typeof IndustriasIndustriaRoute
  '/industrias/siderurgicas': typeof IndustriasSiderurgicasRoute
  '/industrias/varejo': typeof IndustriasVarejoRoute
  '/recursos/guias': typeof RecursosGuiasRoute
  '/recursos/integracoes': typeof RecursosIntegracoesRoute
  '/shipper/esg': typeof ShipperEsgRoute
  '/shipper/payments': typeof ShipperPaymentsRoute
  '/shipper/settings': typeof ShipperSettingsRoute
  '/sobre/pilares': typeof SobrePilaresRoute
  '/sobre/visao': typeof SobreVisaoRoute
  '/solucoes/control-tower': typeof SolucoesControlTowerRoute
  '/solucoes/managed-logistics': typeof SolucoesManagedLogisticsRoute
  '/solucoes/steelgo-network': typeof SolucoesSteelgoNetworkRoute
  '/solucoes/steelgo-pay': typeof SolucoesSteelgoPayRoute
  '/solucoes/steelgo-platform': typeof SolucoesSteelgoPlatformRoute
  '/suporte/ajuda': typeof SuporteAjudaRoute
  '/suporte/canais': typeof SuporteCanaisRoute
  '/tecnologia/ai-orchestration-engine': typeof TecnologiaAiOrchestrationEngineRoute
  '/tecnologia/compliance-suite': typeof TecnologiaComplianceSuiteRoute
  '/tecnologia/driver-app': typeof TecnologiaDriverAppRoute
  '/tecnologia/open-api-ecosystem': typeof TecnologiaOpenApiEcosystemRoute
  '/tecnologia/steel-cargo-passport': typeof TecnologiaSteelCargoPassportRoute
  '/transportadoras/homologacao': typeof TransportadorasHomologacaoRoute
  '/transportadoras/viagens': typeof TransportadorasViagensRoute
  '/admin': typeof AdminIndexRoute
  '/carrier': typeof CarrierIndexRoute
  '/driver': typeof DriverIndexRoute
  '/shipper': typeof ShipperIndexRoute
  '/admin/disputes/$id': typeof AdminDisputesIdRoute
  '/admin/operations/$id': typeof AdminOperationsIdRoute
  '/admin/operations/governance': typeof AdminOperationsGovernanceRoute
  '/carrier/contracts/$id': typeof CarrierContractsIdRoute
  '/carrier/disputes/$id': typeof CarrierDisputesIdRoute
  '/carrier/trips/$id': typeof CarrierTripsIdRoute
  '/shipper/contracts/$id': typeof ShipperContractsIdRoute
  '/shipper/disputes/$id': typeof ShipperDisputesIdRoute
  '/shipper/freights/$id': typeof ShipperFreightsIdRoute
  '/shipper/freights/new': typeof ShipperFreightsNewRoute
  '/shipper/payment/$contractId': typeof ShipperPaymentContractIdRoute
  '/shipper/review/$contractId': typeof ShipperReviewContractIdRoute
  '/shipper/trips/$id': typeof ShipperTripsIdRoute
  '/admin/disputes': typeof AdminDisputesIndexRoute
  '/admin/operations': typeof AdminOperationsIndexRoute
  '/carrier/contracts': typeof CarrierContractsIndexRoute
  '/carrier/disputes': typeof CarrierDisputesIndexRoute
  '/carrier/trips': typeof CarrierTripsIndexRoute
  '/shipper/contracts': typeof ShipperContractsIndexRoute
  '/shipper/disputes': typeof ShipperDisputesIndexRoute
  '/shipper/freights': typeof ShipperFreightsIndexRoute
  '/shipper/trips': typeof ShipperTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrier': typeof CarrierRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRouteWithChildren
  '/esg': typeof EsgRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industrias': typeof IndustriasRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recursos': typeof RecursosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shipper': typeof ShipperRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/suporte': typeof SuporteRoute
  '/tecnologia': typeof TecnologiaRoute
  '/terms': typeof TermsRoute
  '/transportadoras': typeof TransportadorasRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/carriers': typeof AdminCarriersRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/esg': typeof AdminEsgRoute
  '/admin/freights': typeof AdminFreightsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/carrier/active': typeof CarrierActiveRoute
  '/carrier/bids': typeof CarrierBidsRoute
  '/carrier/drivers': typeof CarrierDriversRoute
  '/carrier/fleet': typeof CarrierFleetRoute
  '/carrier/marketplace': typeof CarrierMarketplaceRoute
  '/carrier/payments': typeof CarrierPaymentsRoute
  '/carrier/payouts': typeof CarrierPayoutsRoute
  '/carrier/score': typeof CarrierScoreRoute
  '/carrier/settings': typeof CarrierSettingsRoute
  '/carrier/vehicles': typeof CarrierVehiclesRoute
  '/contato_/comercial': typeof ContatoComercialRoute
  '/driver/checkpoint': typeof DriverCheckpointRoute
  '/driver/delivery-complete': typeof DriverDeliveryCompleteRoute
  '/driver/docs': typeof DriverDocsRoute
  '/driver/exception': typeof DriverExceptionRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/panic': typeof DriverPanicRoute
  '/driver/pod': typeof DriverPodRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/return-receipt': typeof DriverReturnReceiptRoute
  '/esg_/calculadora': typeof EsgCalculadoraRoute
  '/esg_/eficiencia': typeof EsgEficienciaRoute
  '/esg_/indicadores': typeof EsgIndicadoresRoute
  '/esg_/steelgo-green': typeof EsgSteelgoGreenRoute
  '/industrias_/distribuidores': typeof IndustriasDistribuidoresRoute
  '/industrias_/industria': typeof IndustriasIndustriaRoute
  '/industrias_/siderurgicas': typeof IndustriasSiderurgicasRoute
  '/industrias_/varejo': typeof IndustriasVarejoRoute
  '/recursos_/guias': typeof RecursosGuiasRoute
  '/recursos_/integracoes': typeof RecursosIntegracoesRoute
  '/shipper/esg': typeof ShipperEsgRoute
  '/shipper/payments': typeof ShipperPaymentsRoute
  '/shipper/settings': typeof ShipperSettingsRoute
  '/sobre_/pilares': typeof SobrePilaresRoute
  '/sobre_/visao': typeof SobreVisaoRoute
  '/solucoes_/control-tower': typeof SolucoesControlTowerRoute
  '/solucoes_/managed-logistics': typeof SolucoesManagedLogisticsRoute
  '/solucoes_/steelgo-network': typeof SolucoesSteelgoNetworkRoute
  '/solucoes_/steelgo-pay': typeof SolucoesSteelgoPayRoute
  '/solucoes_/steelgo-platform': typeof SolucoesSteelgoPlatformRoute
  '/suporte_/ajuda': typeof SuporteAjudaRoute
  '/suporte_/canais': typeof SuporteCanaisRoute
  '/tecnologia_/ai-orchestration-engine': typeof TecnologiaAiOrchestrationEngineRoute
  '/tecnologia_/compliance-suite': typeof TecnologiaComplianceSuiteRoute
  '/tecnologia_/driver-app': typeof TecnologiaDriverAppRoute
  '/tecnologia_/open-api-ecosystem': typeof TecnologiaOpenApiEcosystemRoute
  '/tecnologia_/steel-cargo-passport': typeof TecnologiaSteelCargoPassportRoute
  '/transportadoras_/homologacao': typeof TransportadorasHomologacaoRoute
  '/transportadoras_/viagens': typeof TransportadorasViagensRoute
  '/admin/': typeof AdminIndexRoute
  '/carrier/': typeof CarrierIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/shipper/': typeof ShipperIndexRoute
  '/admin/disputes/$id': typeof AdminDisputesIdRoute
  '/admin/operations/$id': typeof AdminOperationsIdRoute
  '/admin/operations/governance': typeof AdminOperationsGovernanceRoute
  '/carrier/contracts/$id': typeof CarrierContractsIdRoute
  '/carrier/disputes/$id': typeof CarrierDisputesIdRoute
  '/carrier/trips/$id': typeof CarrierTripsIdRoute
  '/shipper/contracts/$id': typeof ShipperContractsIdRoute
  '/shipper/disputes/$id': typeof ShipperDisputesIdRoute
  '/shipper/freights/$id': typeof ShipperFreightsIdRoute
  '/shipper/freights/new': typeof ShipperFreightsNewRoute
  '/shipper/payment/$contractId': typeof ShipperPaymentContractIdRoute
  '/shipper/review/$contractId': typeof ShipperReviewContractIdRoute
  '/shipper/trips/$id': typeof ShipperTripsIdRoute
  '/admin/disputes/': typeof AdminDisputesIndexRoute
  '/admin/operations/': typeof AdminOperationsIndexRoute
  '/carrier/contracts/': typeof CarrierContractsIndexRoute
  '/carrier/disputes/': typeof CarrierDisputesIndexRoute
  '/carrier/trips/': typeof CarrierTripsIndexRoute
  '/shipper/contracts/': typeof ShipperContractsIndexRoute
  '/shipper/disputes/': typeof ShipperDisputesIndexRoute
  '/shipper/freights/': typeof ShipperFreightsIndexRoute
  '/shipper/trips/': typeof ShipperTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrier'
    | '/contato'
    | '/cookies'
    | '/dashboard'
    | '/driver'
    | '/esg'
    | '/forgot-password'
    | '/industrias'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recursos'
    | '/register'
    | '/reset-password'
    | '/shipper'
    | '/sobre'
    | '/solucoes'
    | '/suporte'
    | '/tecnologia'
    | '/terms'
    | '/transportadoras'
    | '/admin/audit'
    | '/admin/carriers'
    | '/admin/contracts'
    | '/admin/esg'
    | '/admin/freights'
    | '/admin/payments'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/carrier/active'
    | '/carrier/bids'
    | '/carrier/drivers'
    | '/carrier/fleet'
    | '/carrier/marketplace'
    | '/carrier/payments'
    | '/carrier/payouts'
    | '/carrier/score'
    | '/carrier/settings'
    | '/carrier/vehicles'
    | '/contato/comercial'
    | '/driver/checkpoint'
    | '/driver/delivery-complete'
    | '/driver/docs'
    | '/driver/exception'
    | '/driver/history'
    | '/driver/panic'
    | '/driver/pod'
    | '/driver/profile'
    | '/driver/return-receipt'
    | '/esg/calculadora'
    | '/esg/eficiencia'
    | '/esg/indicadores'
    | '/esg/steelgo-green'
    | '/industrias/distribuidores'
    | '/industrias/industria'
    | '/industrias/siderurgicas'
    | '/industrias/varejo'
    | '/recursos/guias'
    | '/recursos/integracoes'
    | '/shipper/esg'
    | '/shipper/payments'
    | '/shipper/settings'
    | '/sobre/pilares'
    | '/sobre/visao'
    | '/solucoes/control-tower'
    | '/solucoes/managed-logistics'
    | '/solucoes/steelgo-network'
    | '/solucoes/steelgo-pay'
    | '/solucoes/steelgo-platform'
    | '/suporte/ajuda'
    | '/suporte/canais'
    | '/tecnologia/ai-orchestration-engine'
    | '/tecnologia/compliance-suite'
    | '/tecnologia/driver-app'
    | '/tecnologia/open-api-ecosystem'
    | '/tecnologia/steel-cargo-passport'
    | '/transportadoras/homologacao'
    | '/transportadoras/viagens'
    | '/admin/'
    | '/carrier/'
    | '/driver/'
    | '/shipper/'
    | '/admin/disputes/$id'
    | '/admin/operations/$id'
    | '/admin/operations/governance'
    | '/carrier/contracts/$id'
    | '/carrier/disputes/$id'
    | '/carrier/trips/$id'
    | '/shipper/contracts/$id'
    | '/shipper/disputes/$id'
    | '/shipper/freights/$id'
    | '/shipper/freights/new'
    | '/shipper/payment/$contractId'
    | '/shipper/review/$contractId'
    | '/shipper/trips/$id'
    | '/admin/disputes/'
    | '/admin/operations/'
    | '/carrier/contracts/'
    | '/carrier/disputes/'
    | '/carrier/trips/'
    | '/shipper/contracts/'
    | '/shipper/disputes/'
    | '/shipper/freights/'
    | '/shipper/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/cookies'
    | '/dashboard'
    | '/esg'
    | '/forgot-password'
    | '/industrias'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recursos'
    | '/register'
    | '/reset-password'
    | '/sobre'
    | '/solucoes'
    | '/suporte'
    | '/tecnologia'
    | '/terms'
    | '/transportadoras'
    | '/admin/audit'
    | '/admin/carriers'
    | '/admin/contracts'
    | '/admin/esg'
    | '/admin/freights'
    | '/admin/payments'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/carrier/active'
    | '/carrier/bids'
    | '/carrier/drivers'
    | '/carrier/fleet'
    | '/carrier/marketplace'
    | '/carrier/payments'
    | '/carrier/payouts'
    | '/carrier/score'
    | '/carrier/settings'
    | '/carrier/vehicles'
    | '/contato/comercial'
    | '/driver/checkpoint'
    | '/driver/delivery-complete'
    | '/driver/docs'
    | '/driver/exception'
    | '/driver/history'
    | '/driver/panic'
    | '/driver/pod'
    | '/driver/profile'
    | '/driver/return-receipt'
    | '/esg/calculadora'
    | '/esg/eficiencia'
    | '/esg/indicadores'
    | '/esg/steelgo-green'
    | '/industrias/distribuidores'
    | '/industrias/industria'
    | '/industrias/siderurgicas'
    | '/industrias/varejo'
    | '/recursos/guias'
    | '/recursos/integracoes'
    | '/shipper/esg'
    | '/shipper/payments'
    | '/shipper/settings'
    | '/sobre/pilares'
    | '/sobre/visao'
    | '/solucoes/control-tower'
    | '/solucoes/managed-logistics'
    | '/solucoes/steelgo-network'
    | '/solucoes/steelgo-pay'
    | '/solucoes/steelgo-platform'
    | '/suporte/ajuda'
    | '/suporte/canais'
    | '/tecnologia/ai-orchestration-engine'
    | '/tecnologia/compliance-suite'
    | '/tecnologia/driver-app'
    | '/tecnologia/open-api-ecosystem'
    | '/tecnologia/steel-cargo-passport'
    | '/transportadoras/homologacao'
    | '/transportadoras/viagens'
    | '/admin'
    | '/carrier'
    | '/driver'
    | '/shipper'
    | '/admin/disputes/$id'
    | '/admin/operations/$id'
    | '/admin/operations/governance'
    | '/carrier/contracts/$id'
    | '/carrier/disputes/$id'
    | '/carrier/trips/$id'
    | '/shipper/contracts/$id'
    | '/shipper/disputes/$id'
    | '/shipper/freights/$id'
    | '/shipper/freights/new'
    | '/shipper/payment/$contractId'
    | '/shipper/review/$contractId'
    | '/shipper/trips/$id'
    | '/admin/disputes'
    | '/admin/operations'
    | '/carrier/contracts'
    | '/carrier/disputes'
    | '/carrier/trips'
    | '/shipper/contracts'
    | '/shipper/disputes'
    | '/shipper/freights'
    | '/shipper/trips'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrier'
    | '/contato'
    | '/cookies'
    | '/dashboard'
    | '/driver'
    | '/esg'
    | '/forgot-password'
    | '/industrias'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recursos'
    | '/register'
    | '/reset-password'
    | '/shipper'
    | '/sobre'
    | '/solucoes'
    | '/suporte'
    | '/tecnologia'
    | '/terms'
    | '/transportadoras'
    | '/admin/audit'
    | '/admin/carriers'
    | '/admin/contracts'
    | '/admin/esg'
    | '/admin/freights'
    | '/admin/payments'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/carrier/active'
    | '/carrier/bids'
    | '/carrier/drivers'
    | '/carrier/fleet'
    | '/carrier/marketplace'
    | '/carrier/payments'
    | '/carrier/payouts'
    | '/carrier/score'
    | '/carrier/settings'
    | '/carrier/vehicles'
    | '/contato_/comercial'
    | '/driver/checkpoint'
    | '/driver/delivery-complete'
    | '/driver/docs'
    | '/driver/exception'
    | '/driver/history'
    | '/driver/panic'
    | '/driver/pod'
    | '/driver/profile'
    | '/driver/return-receipt'
    | '/esg_/calculadora'
    | '/esg_/eficiencia'
    | '/esg_/indicadores'
    | '/esg_/steelgo-green'
    | '/industrias_/distribuidores'
    | '/industrias_/industria'
    | '/industrias_/siderurgicas'
    | '/industrias_/varejo'
    | '/recursos_/guias'
    | '/recursos_/integracoes'
    | '/shipper/esg'
    | '/shipper/payments'
    | '/shipper/settings'
    | '/sobre_/pilares'
    | '/sobre_/visao'
    | '/solucoes_/control-tower'
    | '/solucoes_/managed-logistics'
    | '/solucoes_/steelgo-network'
    | '/solucoes_/steelgo-pay'
    | '/solucoes_/steelgo-platform'
    | '/suporte_/ajuda'
    | '/suporte_/canais'
    | '/tecnologia_/ai-orchestration-engine'
    | '/tecnologia_/compliance-suite'
    | '/tecnologia_/driver-app'
    | '/tecnologia_/open-api-ecosystem'
    | '/tecnologia_/steel-cargo-passport'
    | '/transportadoras_/homologacao'
    | '/transportadoras_/viagens'
    | '/admin/'
    | '/carrier/'
    | '/driver/'
    | '/shipper/'
    | '/admin/disputes/$id'
    | '/admin/operations/$id'
    | '/admin/operations/governance'
    | '/carrier/contracts/$id'
    | '/carrier/disputes/$id'
    | '/carrier/trips/$id'
    | '/shipper/contracts/$id'
    | '/shipper/disputes/$id'
    | '/shipper/freights/$id'
    | '/shipper/freights/new'
    | '/shipper/payment/$contractId'
    | '/shipper/review/$contractId'
    | '/shipper/trips/$id'
    | '/admin/disputes/'
    | '/admin/operations/'
    | '/carrier/contracts/'
    | '/carrier/disputes/'
    | '/carrier/trips/'
    | '/shipper/contracts/'
    | '/shipper/disputes/'
    | '/shipper/freights/'
    | '/shipper/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarrierRoute: typeof CarrierRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DriverRoute: typeof DriverRouteWithChildren
  EsgRoute: typeof EsgRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndustriasRoute: typeof IndustriasRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecursosRoute: typeof RecursosRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShipperRoute: typeof ShipperRouteWithChildren
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
  SuporteRoute: typeof SuporteRoute
  TecnologiaRoute: typeof TecnologiaRoute
  TermsRoute: typeof TermsRoute
  TransportadorasRoute: typeof TransportadorasRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ContatoComercialRoute: typeof ContatoComercialRoute
  EsgCalculadoraRoute: typeof EsgCalculadoraRoute
  EsgEficienciaRoute: typeof EsgEficienciaRoute
  EsgIndicadoresRoute: typeof EsgIndicadoresRoute
  EsgSteelgoGreenRoute: typeof EsgSteelgoGreenRoute
  IndustriasDistribuidoresRoute: typeof IndustriasDistribuidoresRoute
  IndustriasIndustriaRoute: typeof IndustriasIndustriaRoute
  IndustriasSiderurgicasRoute: typeof IndustriasSiderurgicasRoute
  IndustriasVarejoRoute: typeof IndustriasVarejoRoute
  RecursosGuiasRoute: typeof RecursosGuiasRoute
  RecursosIntegracoesRoute: typeof RecursosIntegracoesRoute
  SobrePilaresRoute: typeof SobrePilaresRoute
  SobreVisaoRoute: typeof SobreVisaoRoute
  SolucoesControlTowerRoute: typeof SolucoesControlTowerRoute
  SolucoesManagedLogisticsRoute: typeof SolucoesManagedLogisticsRoute
  SolucoesSteelgoNetworkRoute: typeof SolucoesSteelgoNetworkRoute
  SolucoesSteelgoPayRoute: typeof SolucoesSteelgoPayRoute
  SolucoesSteelgoPlatformRoute: typeof SolucoesSteelgoPlatformRoute
  SuporteAjudaRoute: typeof SuporteAjudaRoute
  SuporteCanaisRoute: typeof SuporteCanaisRoute
  TecnologiaAiOrchestrationEngineRoute: typeof TecnologiaAiOrchestrationEngineRoute
  TecnologiaComplianceSuiteRoute: typeof TecnologiaComplianceSuiteRoute
  TecnologiaDriverAppRoute: typeof TecnologiaDriverAppRoute
  TecnologiaOpenApiEcosystemRoute: typeof TecnologiaOpenApiEcosystemRoute
  TecnologiaSteelCargoPassportRoute: typeof TecnologiaSteelCargoPassportRoute
  TransportadorasHomologacaoRoute: typeof TransportadorasHomologacaoRoute
  TransportadorasViagensRoute: typeof TransportadorasViagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transportadoras': {
      id: '/transportadoras'
      path: '/transportadoras'
      fullPath: '/transportadoras'
      preLoaderRoute: typeof TransportadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipper': {
      id: '/shipper'
      path: '/shipper'
      fullPath: '/shipper'
      preLoaderRoute: typeof ShipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias': {
      id: '/industrias'
      path: '/industrias'
      fullPath: '/industrias'
      preLoaderRoute: typeof IndustriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrier': {
      id: '/carrier'
      path: '/carrier'
      fullPath: '/carrier'
      preLoaderRoute: typeof CarrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipper/': {
      id: '/shipper/'
      path: '/'
      fullPath: '/shipper/'
      preLoaderRoute: typeof ShipperIndexRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/carrier/': {
      id: '/carrier/'
      path: '/'
      fullPath: '/carrier/'
      preLoaderRoute: typeof CarrierIndexRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/transportadoras_/viagens': {
      id: '/transportadoras_/viagens'
      path: '/transportadoras/viagens'
      fullPath: '/transportadoras/viagens'
      preLoaderRoute: typeof TransportadorasViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportadoras_/homologacao': {
      id: '/transportadoras_/homologacao'
      path: '/transportadoras/homologacao'
      fullPath: '/transportadoras/homologacao'
      preLoaderRoute: typeof TransportadorasHomologacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia_/steel-cargo-passport': {
      id: '/tecnologia_/steel-cargo-passport'
      path: '/tecnologia/steel-cargo-passport'
      fullPath: '/tecnologia/steel-cargo-passport'
      preLoaderRoute: typeof TecnologiaSteelCargoPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia_/open-api-ecosystem': {
      id: '/tecnologia_/open-api-ecosystem'
      path: '/tecnologia/open-api-ecosystem'
      fullPath: '/tecnologia/open-api-ecosystem'
      preLoaderRoute: typeof TecnologiaOpenApiEcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia_/driver-app': {
      id: '/tecnologia_/driver-app'
      path: '/tecnologia/driver-app'
      fullPath: '/tecnologia/driver-app'
      preLoaderRoute: typeof TecnologiaDriverAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia_/compliance-suite': {
      id: '/tecnologia_/compliance-suite'
      path: '/tecnologia/compliance-suite'
      fullPath: '/tecnologia/compliance-suite'
      preLoaderRoute: typeof TecnologiaComplianceSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia_/ai-orchestration-engine': {
      id: '/tecnologia_/ai-orchestration-engine'
      path: '/tecnologia/ai-orchestration-engine'
      fullPath: '/tecnologia/ai-orchestration-engine'
      preLoaderRoute: typeof TecnologiaAiOrchestrationEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte_/canais': {
      id: '/suporte_/canais'
      path: '/suporte/canais'
      fullPath: '/suporte/canais'
      preLoaderRoute: typeof SuporteCanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte_/ajuda': {
      id: '/suporte_/ajuda'
      path: '/suporte/ajuda'
      fullPath: '/suporte/ajuda'
      preLoaderRoute: typeof SuporteAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes_/steelgo-platform': {
      id: '/solucoes_/steelgo-platform'
      path: '/solucoes/steelgo-platform'
      fullPath: '/solucoes/steelgo-platform'
      preLoaderRoute: typeof SolucoesSteelgoPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes_/steelgo-pay': {
      id: '/solucoes_/steelgo-pay'
      path: '/solucoes/steelgo-pay'
      fullPath: '/solucoes/steelgo-pay'
      preLoaderRoute: typeof SolucoesSteelgoPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes_/steelgo-network': {
      id: '/solucoes_/steelgo-network'
      path: '/solucoes/steelgo-network'
      fullPath: '/solucoes/steelgo-network'
      preLoaderRoute: typeof SolucoesSteelgoNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes_/managed-logistics': {
      id: '/solucoes_/managed-logistics'
      path: '/solucoes/managed-logistics'
      fullPath: '/solucoes/managed-logistics'
      preLoaderRoute: typeof SolucoesManagedLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes_/control-tower': {
      id: '/solucoes_/control-tower'
      path: '/solucoes/control-tower'
      fullPath: '/solucoes/control-tower'
      preLoaderRoute: typeof SolucoesControlTowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre_/visao': {
      id: '/sobre_/visao'
      path: '/sobre/visao'
      fullPath: '/sobre/visao'
      preLoaderRoute: typeof SobreVisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre_/pilares': {
      id: '/sobre_/pilares'
      path: '/sobre/pilares'
      fullPath: '/sobre/pilares'
      preLoaderRoute: typeof SobrePilaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipper/settings': {
      id: '/shipper/settings'
      path: '/settings'
      fullPath: '/shipper/settings'
      preLoaderRoute: typeof ShipperSettingsRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/payments': {
      id: '/shipper/payments'
      path: '/payments'
      fullPath: '/shipper/payments'
      preLoaderRoute: typeof ShipperPaymentsRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/esg': {
      id: '/shipper/esg'
      path: '/esg'
      fullPath: '/shipper/esg'
      preLoaderRoute: typeof ShipperEsgRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/recursos_/integracoes': {
      id: '/recursos_/integracoes'
      path: '/recursos/integracoes'
      fullPath: '/recursos/integracoes'
      preLoaderRoute: typeof RecursosIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos_/guias': {
      id: '/recursos_/guias'
      path: '/recursos/guias'
      fullPath: '/recursos/guias'
      preLoaderRoute: typeof RecursosGuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias_/varejo': {
      id: '/industrias_/varejo'
      path: '/industrias/varejo'
      fullPath: '/industrias/varejo'
      preLoaderRoute: typeof IndustriasVarejoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias_/siderurgicas': {
      id: '/industrias_/siderurgicas'
      path: '/industrias/siderurgicas'
      fullPath: '/industrias/siderurgicas'
      preLoaderRoute: typeof IndustriasSiderurgicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias_/industria': {
      id: '/industrias_/industria'
      path: '/industrias/industria'
      fullPath: '/industrias/industria'
      preLoaderRoute: typeof IndustriasIndustriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias_/distribuidores': {
      id: '/industrias_/distribuidores'
      path: '/industrias/distribuidores'
      fullPath: '/industrias/distribuidores'
      preLoaderRoute: typeof IndustriasDistribuidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg_/steelgo-green': {
      id: '/esg_/steelgo-green'
      path: '/esg/steelgo-green'
      fullPath: '/esg/steelgo-green'
      preLoaderRoute: typeof EsgSteelgoGreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg_/indicadores': {
      id: '/esg_/indicadores'
      path: '/esg/indicadores'
      fullPath: '/esg/indicadores'
      preLoaderRoute: typeof EsgIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg_/eficiencia': {
      id: '/esg_/eficiencia'
      path: '/esg/eficiencia'
      fullPath: '/esg/eficiencia'
      preLoaderRoute: typeof EsgEficienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg_/calculadora': {
      id: '/esg_/calculadora'
      path: '/esg/calculadora'
      fullPath: '/esg/calculadora'
      preLoaderRoute: typeof EsgCalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/return-receipt': {
      id: '/driver/return-receipt'
      path: '/return-receipt'
      fullPath: '/driver/return-receipt'
      preLoaderRoute: typeof DriverReturnReceiptRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/pod': {
      id: '/driver/pod'
      path: '/pod'
      fullPath: '/driver/pod'
      preLoaderRoute: typeof DriverPodRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/panic': {
      id: '/driver/panic'
      path: '/panic'
      fullPath: '/driver/panic'
      preLoaderRoute: typeof DriverPanicRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/exception': {
      id: '/driver/exception'
      path: '/exception'
      fullPath: '/driver/exception'
      preLoaderRoute: typeof DriverExceptionRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/docs': {
      id: '/driver/docs'
      path: '/docs'
      fullPath: '/driver/docs'
      preLoaderRoute: typeof DriverDocsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/delivery-complete': {
      id: '/driver/delivery-complete'
      path: '/delivery-complete'
      fullPath: '/driver/delivery-complete'
      preLoaderRoute: typeof DriverDeliveryCompleteRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/checkpoint': {
      id: '/driver/checkpoint'
      path: '/checkpoint'
      fullPath: '/driver/checkpoint'
      preLoaderRoute: typeof DriverCheckpointRouteImport
      parentRoute: typeof DriverRoute
    }
    '/contato_/comercial': {
      id: '/contato_/comercial'
      path: '/contato/comercial'
      fullPath: '/contato/comercial'
      preLoaderRoute: typeof ContatoComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrier/vehicles': {
      id: '/carrier/vehicles'
      path: '/vehicles'
      fullPath: '/carrier/vehicles'
      preLoaderRoute: typeof CarrierVehiclesRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/settings': {
      id: '/carrier/settings'
      path: '/settings'
      fullPath: '/carrier/settings'
      preLoaderRoute: typeof CarrierSettingsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/score': {
      id: '/carrier/score'
      path: '/score'
      fullPath: '/carrier/score'
      preLoaderRoute: typeof CarrierScoreRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/payouts': {
      id: '/carrier/payouts'
      path: '/payouts'
      fullPath: '/carrier/payouts'
      preLoaderRoute: typeof CarrierPayoutsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/payments': {
      id: '/carrier/payments'
      path: '/payments'
      fullPath: '/carrier/payments'
      preLoaderRoute: typeof CarrierPaymentsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/marketplace': {
      id: '/carrier/marketplace'
      path: '/marketplace'
      fullPath: '/carrier/marketplace'
      preLoaderRoute: typeof CarrierMarketplaceRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/fleet': {
      id: '/carrier/fleet'
      path: '/fleet'
      fullPath: '/carrier/fleet'
      preLoaderRoute: typeof CarrierFleetRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/drivers': {
      id: '/carrier/drivers'
      path: '/drivers'
      fullPath: '/carrier/drivers'
      preLoaderRoute: typeof CarrierDriversRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/bids': {
      id: '/carrier/bids'
      path: '/bids'
      fullPath: '/carrier/bids'
      preLoaderRoute: typeof CarrierBidsRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/active': {
      id: '/carrier/active'
      path: '/active'
      fullPath: '/carrier/active'
      preLoaderRoute: typeof CarrierActiveRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/freights': {
      id: '/admin/freights'
      path: '/freights'
      fullPath: '/admin/freights'
      preLoaderRoute: typeof AdminFreightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/esg': {
      id: '/admin/esg'
      path: '/esg'
      fullPath: '/admin/esg'
      preLoaderRoute: typeof AdminEsgRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carriers': {
      id: '/admin/carriers'
      path: '/carriers'
      fullPath: '/admin/carriers'
      preLoaderRoute: typeof AdminCarriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shipper/trips/': {
      id: '/shipper/trips/'
      path: '/trips'
      fullPath: '/shipper/trips/'
      preLoaderRoute: typeof ShipperTripsIndexRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/freights/': {
      id: '/shipper/freights/'
      path: '/freights'
      fullPath: '/shipper/freights/'
      preLoaderRoute: typeof ShipperFreightsIndexRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/disputes/': {
      id: '/shipper/disputes/'
      path: '/disputes'
      fullPath: '/shipper/disputes/'
      preLoaderRoute: typeof ShipperDisputesIndexRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/contracts/': {
      id: '/shipper/contracts/'
      path: '/contracts'
      fullPath: '/shipper/contracts/'
      preLoaderRoute: typeof ShipperContractsIndexRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/carrier/trips/': {
      id: '/carrier/trips/'
      path: '/trips'
      fullPath: '/carrier/trips/'
      preLoaderRoute: typeof CarrierTripsIndexRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/disputes/': {
      id: '/carrier/disputes/'
      path: '/disputes'
      fullPath: '/carrier/disputes/'
      preLoaderRoute: typeof CarrierDisputesIndexRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/contracts/': {
      id: '/carrier/contracts/'
      path: '/contracts'
      fullPath: '/carrier/contracts/'
      preLoaderRoute: typeof CarrierContractsIndexRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/admin/operations/': {
      id: '/admin/operations/'
      path: '/operations'
      fullPath: '/admin/operations/'
      preLoaderRoute: typeof AdminOperationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes/': {
      id: '/admin/disputes/'
      path: '/disputes'
      fullPath: '/admin/disputes/'
      preLoaderRoute: typeof AdminDisputesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shipper/trips/$id': {
      id: '/shipper/trips/$id'
      path: '/trips/$id'
      fullPath: '/shipper/trips/$id'
      preLoaderRoute: typeof ShipperTripsIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/review/$contractId': {
      id: '/shipper/review/$contractId'
      path: '/review/$contractId'
      fullPath: '/shipper/review/$contractId'
      preLoaderRoute: typeof ShipperReviewContractIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/payment/$contractId': {
      id: '/shipper/payment/$contractId'
      path: '/payment/$contractId'
      fullPath: '/shipper/payment/$contractId'
      preLoaderRoute: typeof ShipperPaymentContractIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/freights/new': {
      id: '/shipper/freights/new'
      path: '/freights/new'
      fullPath: '/shipper/freights/new'
      preLoaderRoute: typeof ShipperFreightsNewRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/freights/$id': {
      id: '/shipper/freights/$id'
      path: '/freights/$id'
      fullPath: '/shipper/freights/$id'
      preLoaderRoute: typeof ShipperFreightsIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/disputes/$id': {
      id: '/shipper/disputes/$id'
      path: '/disputes/$id'
      fullPath: '/shipper/disputes/$id'
      preLoaderRoute: typeof ShipperDisputesIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/shipper/contracts/$id': {
      id: '/shipper/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/shipper/contracts/$id'
      preLoaderRoute: typeof ShipperContractsIdRouteImport
      parentRoute: typeof ShipperRoute
    }
    '/carrier/trips/$id': {
      id: '/carrier/trips/$id'
      path: '/trips/$id'
      fullPath: '/carrier/trips/$id'
      preLoaderRoute: typeof CarrierTripsIdRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/disputes/$id': {
      id: '/carrier/disputes/$id'
      path: '/disputes/$id'
      fullPath: '/carrier/disputes/$id'
      preLoaderRoute: typeof CarrierDisputesIdRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/carrier/contracts/$id': {
      id: '/carrier/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/carrier/contracts/$id'
      preLoaderRoute: typeof CarrierContractsIdRouteImport
      parentRoute: typeof CarrierRoute
    }
    '/admin/operations/governance': {
      id: '/admin/operations/governance'
      path: '/operations/governance'
      fullPath: '/admin/operations/governance'
      preLoaderRoute: typeof AdminOperationsGovernanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations/$id': {
      id: '/admin/operations/$id'
      path: '/operations/$id'
      fullPath: '/admin/operations/$id'
      preLoaderRoute: typeof AdminOperationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes/$id': {
      id: '/admin/disputes/$id'
      path: '/disputes/$id'
      fullPath: '/admin/disputes/$id'
      preLoaderRoute: typeof AdminDisputesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCarriersRoute: typeof AdminCarriersRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminEsgRoute: typeof AdminEsgRoute
  AdminFreightsRoute: typeof AdminFreightsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDisputesIdRoute: typeof AdminDisputesIdRoute
  AdminOperationsIdRoute: typeof AdminOperationsIdRoute
  AdminOperationsGovernanceRoute: typeof AdminOperationsGovernanceRoute
  AdminDisputesIndexRoute: typeof AdminDisputesIndexRoute
  AdminOperationsIndexRoute: typeof AdminOperationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCarriersRoute: AdminCarriersRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminEsgRoute: AdminEsgRoute,
  AdminFreightsRoute: AdminFreightsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDisputesIdRoute: AdminDisputesIdRoute,
  AdminOperationsIdRoute: AdminOperationsIdRoute,
  AdminOperationsGovernanceRoute: AdminOperationsGovernanceRoute,
  AdminDisputesIndexRoute: AdminDisputesIndexRoute,
  AdminOperationsIndexRoute: AdminOperationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CarrierRouteChildren {
  CarrierActiveRoute: typeof CarrierActiveRoute
  CarrierBidsRoute: typeof CarrierBidsRoute
  CarrierDriversRoute: typeof CarrierDriversRoute
  CarrierFleetRoute: typeof CarrierFleetRoute
  CarrierMarketplaceRoute: typeof CarrierMarketplaceRoute
  CarrierPaymentsRoute: typeof CarrierPaymentsRoute
  CarrierPayoutsRoute: typeof CarrierPayoutsRoute
  CarrierScoreRoute: typeof CarrierScoreRoute
  CarrierSettingsRoute: typeof CarrierSettingsRoute
  CarrierVehiclesRoute: typeof CarrierVehiclesRoute
  CarrierIndexRoute: typeof CarrierIndexRoute
  CarrierContractsIdRoute: typeof CarrierContractsIdRoute
  CarrierDisputesIdRoute: typeof CarrierDisputesIdRoute
  CarrierTripsIdRoute: typeof CarrierTripsIdRoute
  CarrierContractsIndexRoute: typeof CarrierContractsIndexRoute
  CarrierDisputesIndexRoute: typeof CarrierDisputesIndexRoute
  CarrierTripsIndexRoute: typeof CarrierTripsIndexRoute
}

const CarrierRouteChildren: CarrierRouteChildren = {
  CarrierActiveRoute: CarrierActiveRoute,
  CarrierBidsRoute: CarrierBidsRoute,
  CarrierDriversRoute: CarrierDriversRoute,
  CarrierFleetRoute: CarrierFleetRoute,
  CarrierMarketplaceRoute: CarrierMarketplaceRoute,
  CarrierPaymentsRoute: CarrierPaymentsRoute,
  CarrierPayoutsRoute: CarrierPayoutsRoute,
  CarrierScoreRoute: CarrierScoreRoute,
  CarrierSettingsRoute: CarrierSettingsRoute,
  CarrierVehiclesRoute: CarrierVehiclesRoute,
  CarrierIndexRoute: CarrierIndexRoute,
  CarrierContractsIdRoute: CarrierContractsIdRoute,
  CarrierDisputesIdRoute: CarrierDisputesIdRoute,
  CarrierTripsIdRoute: CarrierTripsIdRoute,
  CarrierContractsIndexRoute: CarrierContractsIndexRoute,
  CarrierDisputesIndexRoute: CarrierDisputesIndexRoute,
  CarrierTripsIndexRoute: CarrierTripsIndexRoute,
}

const CarrierRouteWithChildren =
  CarrierRoute._addFileChildren(CarrierRouteChildren)

interface DriverRouteChildren {
  DriverCheckpointRoute: typeof DriverCheckpointRoute
  DriverDeliveryCompleteRoute: typeof DriverDeliveryCompleteRoute
  DriverDocsRoute: typeof DriverDocsRoute
  DriverExceptionRoute: typeof DriverExceptionRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverPanicRoute: typeof DriverPanicRoute
  DriverPodRoute: typeof DriverPodRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverReturnReceiptRoute: typeof DriverReturnReceiptRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverCheckpointRoute: DriverCheckpointRoute,
  DriverDeliveryCompleteRoute: DriverDeliveryCompleteRoute,
  DriverDocsRoute: DriverDocsRoute,
  DriverExceptionRoute: DriverExceptionRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverPanicRoute: DriverPanicRoute,
  DriverPodRoute: DriverPodRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverReturnReceiptRoute: DriverReturnReceiptRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface ShipperRouteChildren {
  ShipperEsgRoute: typeof ShipperEsgRoute
  ShipperPaymentsRoute: typeof ShipperPaymentsRoute
  ShipperSettingsRoute: typeof ShipperSettingsRoute
  ShipperIndexRoute: typeof ShipperIndexRoute
  ShipperContractsIdRoute: typeof ShipperContractsIdRoute
  ShipperDisputesIdRoute: typeof ShipperDisputesIdRoute
  ShipperFreightsIdRoute: typeof ShipperFreightsIdRoute
  ShipperFreightsNewRoute: typeof ShipperFreightsNewRoute
  ShipperPaymentContractIdRoute: typeof ShipperPaymentContractIdRoute
  ShipperReviewContractIdRoute: typeof ShipperReviewContractIdRoute
  ShipperTripsIdRoute: typeof ShipperTripsIdRoute
  ShipperContractsIndexRoute: typeof ShipperContractsIndexRoute
  ShipperDisputesIndexRoute: typeof ShipperDisputesIndexRoute
  ShipperFreightsIndexRoute: typeof ShipperFreightsIndexRoute
  ShipperTripsIndexRoute: typeof ShipperTripsIndexRoute
}

const ShipperRouteChildren: ShipperRouteChildren = {
  ShipperEsgRoute: ShipperEsgRoute,
  ShipperPaymentsRoute: ShipperPaymentsRoute,
  ShipperSettingsRoute: ShipperSettingsRoute,
  ShipperIndexRoute: ShipperIndexRoute,
  ShipperContractsIdRoute: ShipperContractsIdRoute,
  ShipperDisputesIdRoute: ShipperDisputesIdRoute,
  ShipperFreightsIdRoute: ShipperFreightsIdRoute,
  ShipperFreightsNewRoute: ShipperFreightsNewRoute,
  ShipperPaymentContractIdRoute: ShipperPaymentContractIdRoute,
  ShipperReviewContractIdRoute: ShipperReviewContractIdRoute,
  ShipperTripsIdRoute: ShipperTripsIdRoute,
  ShipperContractsIndexRoute: ShipperContractsIndexRoute,
  ShipperDisputesIndexRoute: ShipperDisputesIndexRoute,
  ShipperFreightsIndexRoute: ShipperFreightsIndexRoute,
  ShipperTripsIndexRoute: ShipperTripsIndexRoute,
}

const ShipperRouteWithChildren =
  ShipperRoute._addFileChildren(ShipperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarrierRoute: CarrierRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DriverRoute: DriverRouteWithChildren,
  EsgRoute: EsgRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndustriasRoute: IndustriasRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RecursosRoute: RecursosRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShipperRoute: ShipperRouteWithChildren,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
  SuporteRoute: SuporteRoute,
  TecnologiaRoute: TecnologiaRoute,
  TermsRoute: TermsRoute,
  TransportadorasRoute: TransportadorasRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ContatoComercialRoute: ContatoComercialRoute,
  EsgCalculadoraRoute: EsgCalculadoraRoute,
  EsgEficienciaRoute: EsgEficienciaRoute,
  EsgIndicadoresRoute: EsgIndicadoresRoute,
  EsgSteelgoGreenRoute: EsgSteelgoGreenRoute,
  IndustriasDistribuidoresRoute: IndustriasDistribuidoresRoute,
  IndustriasIndustriaRoute: IndustriasIndustriaRoute,
  IndustriasSiderurgicasRoute: IndustriasSiderurgicasRoute,
  IndustriasVarejoRoute: IndustriasVarejoRoute,
  RecursosGuiasRoute: RecursosGuiasRoute,
  RecursosIntegracoesRoute: RecursosIntegracoesRoute,
  SobrePilaresRoute: SobrePilaresRoute,
  SobreVisaoRoute: SobreVisaoRoute,
  SolucoesControlTowerRoute: SolucoesControlTowerRoute,
  SolucoesManagedLogisticsRoute: SolucoesManagedLogisticsRoute,
  SolucoesSteelgoNetworkRoute: SolucoesSteelgoNetworkRoute,
  SolucoesSteelgoPayRoute: SolucoesSteelgoPayRoute,
  SolucoesSteelgoPlatformRoute: SolucoesSteelgoPlatformRoute,
  SuporteAjudaRoute: SuporteAjudaRoute,
  SuporteCanaisRoute: SuporteCanaisRoute,
  TecnologiaAiOrchestrationEngineRoute: TecnologiaAiOrchestrationEngineRoute,
  TecnologiaComplianceSuiteRoute: TecnologiaComplianceSuiteRoute,
  TecnologiaDriverAppRoute: TecnologiaDriverAppRoute,
  TecnologiaOpenApiEcosystemRoute: TecnologiaOpenApiEcosystemRoute,
  TecnologiaSteelCargoPassportRoute: TecnologiaSteelCargoPassportRoute,
  TransportadorasHomologacaoRoute: TransportadorasHomologacaoRoute,
  TransportadorasViagensRoute: TransportadorasViagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
